### ISSUE TITLE
While trying to train TSegNet fully, I got IndexError: too many indices for array.

### ISSUE THREAD

**Issue by M-Alsouqi** [limhoyeon/ToothGroupNetwork#14]
Greetings.

I was able to train the centroid prediction of TSegNet.
However when I tried to train the full model as you explained in your Readme, I got this IndexError.

```
teeth-train_1  | Traceback (most recent call last):
teeth-train_1  |   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
teeth-train_1  |     return _run_code(code, main_globals, None,
teeth-train_1  |   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
teeth-train_1  |     exec(code, run_globals)
teeth-train_1  |   File "/opt/algorithm/start_train.py", line 103, in <module>
teeth-train_1  |     runner(config, model)
teeth-train_1  |   File "/opt/algorithm/runner.py", line 55, in runner
teeth-train_1  |     trainner.run()
teeth-train_1  |   File "/opt/algorithm/trainer.py", line 137, in run
teeth-train_1  |     self.train(epoch, train_data_loader, logger)
teeth-train_1  |   File "/opt/algorithm/trainer.py", line 50, in train
teeth-train_1  |     loss = self.model.step(batch_idx, batch_item, "train")
teeth-train_1  |   File "/opt/algorithm/models/tsegnet_model.py", line 72, in step
teeth-train_1  |     output = self.module(inputs)
teeth-train_1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
teeth-train_1  |     result = self.forward(*input, **kwargs)
teeth-train_1  |   File "/opt/algorithm/models/modules/tsegnet.py", line 67, in forward
teeth-train_1  |     center_points = center_points[None,:,:]
teeth-train_1  | IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

```

After further investigation in the code, I found that the algorithm was trying to specify 2 index values in a numpy array that was original a one-dimensional python list.

```
moved_points = gu.torch_to_numpy(l3_xyz + offset_result).T.reshape(-1,3)
moved_points = moved_points[gu.torch_to_numpy(dist_result).reshape(-1)<0.3,:]
dbscan_results = DBSCAN(eps=0.05, min_samples=3).fit(moved_points, 3)
#gu.print_3d(gu.np_to_pcd_with_label(moved_points, dbscan_results.labels_))

center_points = [] # one dimensional list
for label in np.unique(dbscan_results.labels_):
    if label == -1: continue
    center_points.append(moved_points[dbscan_results.labels_==label].mean(axis=0))
center_points = np.array(center_points) # one dimensional numpy array
center_points = center_points[None,:,:] # specifying 2 index values from a one dimensional numpy array
#gu.print_3d(gu.np_to_pcd(moved_points,color=[0,1,0]), center_points[0])

rand_indexes = np.random.permutation(center_points.shape[1])[:8]
center_points = center_points.transpose(0,2,1)[:,:,rand_indexes].transpose(0,2,1)
```

Do you know how I proceed from that?
was something supposed to be concatenated with this numpy array?

**Comment by M-Alsouqi** [comment]
Update!

Apparently the issue causing this error is that DBScan takes all the points as noisy samples.
all the points that enter DBScan yield a -1 label

So I'm left with a list of [-1,-1,-1,-1,...,-1]
This causes the For loop after it yields nothing because it ignores -1
Therefore the center_points list is an empty list and thus the error.



This is weird considering I'm using the exact data you used in the challenge.
I'm also using the same training and val splits.
I haven't modified the training data in anyway nor I have modified the model parameters.

I also tried to change eps from 0.05 to 0.015 as its empirically set as that in the TSegNet paper, but to no avail.

@limhoyeon Can you please consult me on what would be the issue?

**Comment by madhavkrishnan94** [comment]
Hi, I am facing the same issue. Can you let me know how you resolved it?

Any advice @limhoyeon ?

**Comment by 1320740447dsj** [comment]
Hi, I am facing the same issue. Can you let me know how you resolved it? @madhavkrishnan94
