### ISSUE TITLE
Issue installing pointops

### ISSUE THREAD

**Issue by refrantz** [limhoyeon/ToothGroupNetwork#22]
Hello, I created a conda env with the specified version for cuda (11.0) and pytorch (1.7.1) and used the command in the installation section, but an error occurs when installing pointops: 

```
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/6] /usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/subtraction/subtraction_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/subtraction/subtraction_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/subtraction/subtraction_cuda_kernel.o
/usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/subtraction/subtraction_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/subtraction/subtraction_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |
                     ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |
                      ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
[2/6] /usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/knnquery/knnquery_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/knnquery/knnquery_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/knnquery/knnquery_cuda_kernel.o

/usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/knnquery/knnquery_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/knnquery/knnquery_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |
                     ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |
                      ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
[3/6] /usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/interpolation/interpolation_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/interpolation/interpolation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/interpolation/interpolation_cuda_kernel.o
/usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/interpolation/interpolation_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/interpolation/interpolation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |
                     ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |
                      ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
[4/6] /usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/grouping/grouping_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/grouping/grouping_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/grouping/grouping_cuda_kernel.o

/usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/grouping/grouping_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/grouping/grouping_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |
                     ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |
                      ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
[5/6] /usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/aggregation/aggregation_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/aggregation/aggregation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/aggregation/aggregation_cuda_kernel.o
/usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/aggregation/aggregation_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/aggregation/aggregation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |
                     ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |
                      ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
[6/6] /usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/sampling/sampling_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/sampling/sampling_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/sampling/sampling_cuda_kernel.o

/usr/bin/nvcc -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/TH -I/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/THC -I/home/renan/anaconda3/envs/ToothGroupNetwork/include/python3.8 -c -c /home/renan/ToothGroupNetwork/external_libs/pointops/src/sampling/sampling_cuda_kernel.cu -o /home/renan/ToothGroupNetwork/external_libs/pointops/build/temp.linux-x86_64-cpython-38/src/sampling/sampling_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=pointops_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/boxing/impl/boxing.h(100): warning #68-D: integer conversion resulted in a change of sign

/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning #68-D: integer conversion resulted in a change of sign

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |
                     ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |
                      ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    setup(
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/command/install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/renan/anaconda3/envs/ToothGroupNetwork/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

I tried pulling the version from the git that is linked as a suggestion, and the same error occurs. This is my system:

WSL2 (Ubuntu)
I7-12700KF
RTX 3080

**Comment by limhoyeon** [comment]
Have you solved this issue now?

**Comment by refrantz** [comment]
From what I found it's a issue with what versions of cuda the GPU supports, but I ended up focusing on other things and didn't fix this (it might not be fixable without modifying pointops itself)

**Comment by smoothumut** [comment]
removing all 

    include <THC/THC.h>

lines in pointops library solved my problem as indicated in other related issues
