### ISSUE TITLE
start_inference.py error : ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by supgy** [limhoyeon/ToothGroupNetwork#26]
Dear author,
           I used trained model to run start_inference.py and then visualize the predict result use eval_visualize_results.py. An error occurred：
Traceback (most recent call last):
  File "C:\Users\1\Desktop\ToothGroupNetwork-main\eval_visualize_results.py", line 66, in <module>
    IoU, F1, Acc, SEM_ACC, _ = cal_metric(gt_labels, pred_labels, pred_labels) # F1 -> TSA, SEM_ACC -> TIR
  File "C:\Users\1\Desktop\ToothGroupNetwork-main\eval_visualize_results.py", line 58, in cal_metric
    return IOU/len(ins_label_names), F1/len(ins_label_names), ACC/len(ins_label_names), SEM_ACC/len(ins_label_names), IOU_arr
ZeroDivisionError: division by zero

And I notice that label value in in the predict json files all zero. Can you help me?
![图片1](https://github.com/limhoyeon/ToothGroupNetwork/assets/144404526/affeb10b-6f1f-4973-838f-249b2f6d389a)

**Comment by supgy** [comment]
I have solved this problem by reinstall pointops.
