### ISSUE TITLE
Train tgnet_fps and find the error

### ISSUE THREAD

**Issue by Frq-F** [limhoyeon/ToothGroupNetwork#32]
Hello, when I train the tgnet_fps model, I got following error
Traceback (most recent call last):
  File "start_train.py", line 51, in <module>
    runner(config, model)
  File "/workspace/ToothGroupNetwork-main/ToothGroupNetwork-main/runner.py", line 53, in runner
    gen_set = [get_generator_set(config["generator"], False)]
  File "/workspace/ToothGroupNetwork-main/ToothGroupNetwork-main/runner.py", line 28, in get_generator_set
    point_loader = DataLoader(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

How to solve this issue? By the way , I use the challange dataset.

**Comment by Frq-F** [comment]
My base_name_train_fold.txt belike 
00OMSZGW_lower_lower_sampled_points.npy
00OMSZGW_upper_upper_sampled_points.npy
01328DDN_lower_lower_sampled_points.npy......
Is that right? or it should contain input_data_dir_path

**Comment by Frq-F** [comment]
I modify the code ，change the parameter of shuffle from true to false，solve this issue。
point_loader = DataLoader(
            DentalModelGenerator(
                config["input_data_dir_path"], 
                aug_obj_str=config["aug_obj_str"],
                split_with_txt_path=config["train_data_split_txt_path"]
            ), 
            shuffle=False,
            batch_size=config["train_batch_size"],
            collate_fn=collate_fn
        ) 
But my data path is not set right, the train_set=0, validation_set=0.
My input_data_dir_path is set  to the folder where data is stored，and txt file belike
00OMSZGW_lower_lower_sampled_points.npy
00OMSZGW_upper_upper_sampled_points.npy
01328DDN_lower_lower_sampled_points.npy......

**Comment by Frq-F** [comment]
I solve the problem ,txt file should be like 
01328DDN

**Comment by ericnlt** [comment]
> I modify the code ，change the parameter of shuffle from true to false，solve this issue。 point_loader = DataLoader( DentalModelGenerator( config["input_data_dir_path"], aug_obj_str=config["aug_obj_str"], split_with_txt_path=config["train_data_split_txt_path"] ), shuffle=False, batch_size=config["train_batch_size"], collate_fn=collate_fn ) But my data path is not set right, the train_set=0, validation_set=0. My input_data_dir_path is set to the folder where data is stored，and txt file belike 00OMSZGW_lower_lower_sampled_points.npy 00OMSZGW_upper_upper_sampled_points.npy 01328DDN_lower_lower_sampled_points.npy......
What are the correct values for train_set and validation_set? I'm also 0.

**Comment by ericnlt** [comment]
> I solve the problem ,txt file should be like 01328DDN

What's your video card? How long did it take to train tgnet_fps?
