### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by DBSCAN

### ISSUE THREAD

**Issue by cmsbuptvisoin** [limhoyeon/ToothGroupNetwork#41]
args.input_dir_path= H:\teeth\3DTeethSeg\ToothGroupNetwork-main\in_obj
args.split_txt_path= test_id.txt
stl_path_ls= ['H:\\teeth\\3DTeethSeg\\ToothGroupNetwork-main\\in_obj\\00OMSZGW\\00OMSZGW_lower.obj', 'H:\\teeth\\3DTeethSeg\\ToothGroupNetwork-main\\in_obj\\00OMSZGW\\00OMSZGW_upper.obj']
Processing:  0 : H:\teeth\3DTeethSeg\ToothGroupNetwork-main\in_obj\00OMSZGW\00OMSZGW_lower.obj
Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by DBSCAN.
Traceback (most recent call last):
  File "h:\teeth\3DTeethSeg\ToothGroupNetwork-main\predict_utils.py", line 97, in predict
    pred_result = self.chl_pipeline(scan_path)
  File "h:\teeth\3DTeethSeg\ToothGroupNetwork-main\inference_pipelines\inference_pipeline_tgn.py", line 46, in __call__
    first_results = self.get_first_module_results(input_cuda_feats, self.first_module)
  File "h:\teeth\3DTeethSeg\ToothGroupNetwork-main\inference_pipelines\inference_pipeline_tgn.py", line 170, in get_first_module_results
    output = base_model([points])
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "h:\teeth\3DTeethSeg\ToothGroupNetwork-main\models\modules\grouping_network_module.py", line 65, in forward
    fg_points_labels_ls = ou.get_clustering_labels(b_moved_points, whole_cls_1)
  File "h:\teeth\3DTeethSeg\ToothGroupNetwork-main\ops_utils.py", line 98, in get_clustering_labels
    clustering = DBSCAN(eps=0.03, min_samples=30).fit(moved_points[super_point_cond, :], 3)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cluster\_dbscan.py", line 370, in fit
    X = self._validate_data(X, accept_sparse="csr")
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py", line 604, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 969, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by DBSCAN.

**Comment by liiad** [comment]
I had the same problem，to adjust eps and min_samples not worked!

**Comment by hongpengxu779** [comment]
> 我遇到了同样的问题，调整 eps min_samples不起作用！

您好，你们解决这个问题了吗？

**Comment by liiad** [comment]
更换一下库的版本就好了
















在 2024-07-15 16:57:24，"hongpengxu779" ***@***.***> 写道：

我遇到了同样的问题，调整 eps min_samples不起作用！

您好，你们解决这个问题了吗？

**Comment by limhoyeon** [comment]
would you check the issue #42

**Comment by Gayanukaa** [comment]
@limhoyeon
Having same problem running `inference_final.py`
- Using RTX 4070 GPU on the challenge branch with point tops
- Jaws are aligned as mentioned.

Getting above mentioned error pointing towards - ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required.
Meaning no “super‐points” to cluster

The code worked on Kaggle but not on PC
