### ISSUE TITLE
Error during training tgnet_fps

### ISSUE THREAD

**Issue by FengZhongLiuDong** [limhoyeon/ToothGroupNetwork#53]
`
Traceback (most recent call last):
  File "start_train.py", line 59, in <module>
    runner(config, model)
  File "/root/ToothGroupNetwork/runner.py", line 57, in runner
    trainner.run()
  File "/root/ToothGroupNetwork/trainer.py", line 100, in run
    self.train(epoch, train_data_loader)
  File "/root/ToothGroupNetwork/trainer.py", line 31, in train
    loss = self.model.step(batch_idx, batch_item, "train")
  File "/root/ToothGroupNetwork/models/fps_grouping_network_model.py", line 37, in step
    output = self.module(inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/ToothGroupNetwork/models/modules/grouping_network_module.py", line 72, in forward
    nn_crop_indexes = ou.get_nearest_neighbor_idx(org_xyz_cpu, cluster_centroids, self.config["model_parameter"]["crop_sample_size"])
  File "/root/ToothGroupNetwork/ops_utils.py", line 159, in get_nearest_neighbor_idx
    indexs = tree.query(sampled_clusters[batch_idx], k=crop_num, return_distance = False)
  File "sklearn/neighbors/_binary_tree.pxi", line 1106, in sklearn.neighbors._kd_tree.BinaryTree.query
  File "/root/miniconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 938, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
`
Configuration information：
NVIDIA GeForce RTX 4060 Ti
cuda 11.8 pytorch 2.1
At first, I thought it was due to the environment, but I switched to the same environment as the author.But the same error occurred。
NVIDIA GeForce RTX 2080 Ti  
cuda 11.0 pytorch 1.7 
After reviewing others' issues, I recompiled pointops (https://github.com/POSTECH-CVLab/point-transformer), but the problem still persists
Help!

**Comment by FengZhongLiuDong** [comment]
![image](https://github.com/user-attachments/assets/dbf30a41-7dee-467d-a6b3-85e52f62c0de)

**Comment by FengZhongLiuDong** [comment]
![image](https://github.com/user-attachments/assets/218f9fd2-7ed6-47ed-a461-e1862ef98a2c)

**Comment by rebecca0307ss** [comment]
Hi, I'm having the same problem as you, have you solved the problem now?

**Comment by rebecca0307ss** [comment]
> ![image](https://private-user-images.githubusercontent.com/107820293/389197162-dbf30a41-7dee-467d-a6b3-85e52f62c0de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NjYyNzEsIm5iZiI6MTczNDg2NTk3MSwicGF0aCI6Ii8xMDc4MjAyOTMvMzg5MTk3MTYyLWRiZjMwYTQxLTdkZWUtNDY3ZC1hNmIzLTg1ZTUyZjYyYzBkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQxMTEyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGE2ODUxNGE2NzI5YzlmNTMwMGRlYjEzOTU3OWY2Zjk2NThkNWMzZjA0ZTZjN2Q5MWQwZmM0NTZlMGY5Mzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vUTQg7KiPaSFGGzFydpQAGMBCpNBbwd3n-ViaY0rotM)

Hi, I'm having the same problem as you, have you solved the problem now?

**Comment by YangZiz** [comment]
I encountered the same problem, I think it's because the version of the pointops library is incorrect
